name: Build x86/64 openwrt

on:
  push:
    paths:
      - "version"
      - ".github/workflows/**"
      
env:
  CONFIG_FILE: config/x86/64.config
  SOURCE_URL: https://github.com/openwrt/openwrt
  SOURCE_BRANCH: v21.02.2
  TOOLCHAIN_TAG: Build x86/64 openwrt
  CLASH_BINARY_PLATFORM: amd64
  FIRMWARE_RELEASE_UPLOAD: false
  TZ: Asia/Shanghai

jobs:
  Toolchain:
    runs-on: ubuntu-20.04

    steps:
    
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
          CACHE_NAME:  Initialization Environment ubuntu-20.04
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          
      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        id: clone
        run: |
          df -hT $PWD
          git clone $SOURCE_URL -b $SOURCE_BRANCH workspace/openwrt
          cd workspace/openwrt
          echo "OPENWRT_ROOT_PATH=$PWD" >> $GITHUB_ENV
          echo "::set-output name=OPENWRT_ROOT_PATH::$(echo $PWD)"
          
      - name: Update Ip
        run: |
          cd $OPENWRT_ROOT_PATH
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
          
          
      - name: Install Feeds
        run: |
          cd $OPENWRT_ROOT_PATH
          sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
          sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f
      
      - name: Generate Toolchain Config
        run: |
          mv $CONFIG_FILE $OPENWRT_ROOT_PATH/.config
          
#          make -j$(nproc) || make -j1 V=s
      - name: Compile firmware
        run: |
          df -hT $PWD
          cd $OPENWRT_ROOT_PATH
          make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          mv ./bin $PWD/bin
          cd $PWD
          pwd
          
      - name: Deliver bin
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_bin
          path: ./bin/targets
